SlightPHP.lo: /root/SlightPHP/SlightPHP/SlightPHP.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/root/SlightPHP/SlightPHP $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/SlightPHP/SlightPHP/SlightPHP.c -o SlightPHP.lo 
$(phplibdir)/SlightPHP.la: ./SlightPHP.la
	$(LIBTOOL) --mode=install cp ./SlightPHP.la $(phplibdir)

./SlightPHP.la: $(shared_objects_SlightPHP) $(SLIGHTPHP_SHARED_DEPENDENCIES)
	$(LIBTOOL) --mode=link $(CC) $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(LDFLAGS) -o $@ -export-dynamic -avoid-version -prefer-pic -module -rpath $(phplibdir) $(EXTRA_LDFLAGS) $(shared_objects_SlightPHP) $(SLIGHTPHP_SHARED_LIBADD)

